### ISSUE TITLE
How can I get real file name?

### ISSUE THREAD

**Issue by maxkrukov** [jenkinsci/file-parameters-plugin#105]
### What feature do you want to see added?

Real name of uploaded file

**Comment by maxkrukov** [comment]
I found in env variables.   If jenkins param zipfile then zipfile_FILENAME will be real name

**Comment by jglick** [comment]
Could docs be improved to make this clearer?

**Comment by aaronscofield** [comment]
@jglick Hi Jesse, is there a way to get the original upload filename from a file via uploaded the input step of a pipeline?  I tried using the _FILENAME suffix but no luck. Thanks.

`withEnv(["fb64=$fb64"]) {
           sh "echo $fb64_FILENAME"
           sh "echo $fb64 | base64 -d"
}`

**Comment by jglick** [comment]
@aaronscofield no, but I filed #133 with ideas.

**Comment by aaronscofield** [comment]
@jglick Okay, thank you for the response. It would be great to have that feature!

**Comment by marslo** [comment]
finding from build environment works to me

```groovy
String getFilename( String paramName ) {
  env.getEnvironment().find { "${paramName}_FILENAME" == it.key }?.value ?: ''
}
```

**Comment by jkuchnier** [comment]
I'm using input to upload a file during the pipeline execution. Is this still applicable or is there another way to retrieve the filename now?

**Comment by jglick** [comment]
@jkuchnier I think you are looking for #133?

**Comment by ankujuniyal** [comment]
for me its working with {paramName} 
echo "original file name is {paramName}"
jenkins version 2.462.1
