### ISSUE TITLE
Stackoverflowerror -  when using stash parameter in jenkins pipeline jobs  

### ISSUE THREAD

**Issue by selvakumar7991** [jenkinsci/file-parameters-plugin#182]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

using kubernetes jenkins hosted on AWS

jenkins version -  jenkins/jenkins:2.426.1

### Reproduction steps

stashedFile (name: 'Add_file')

### Expected Results

After adding the parameter in jenkins file and then enabled with buildwithparameters

click on build button, not running anything,simply throwing white page

### Actual Results

returning stackoverflow errror in jenkins job

io.jenkins.plugins.file_parameters.StashedFileParameterValue.buildEnvironment(StashedFileParameterValue.java:70)
	at hudson.model.ParametersAction.buildEnvironment(ParametersAction.java:143)
	at hudson.model.Run.getEnvironment(Run.java:2434)

**Comment by selvakumar7991** [comment]
I am interested in contributing if you guide me on how to do that

**Comment by selvakumar7991** [comment]
@jglick could you guide us on how to solve the issue

**Comment by jglick** [comment]
It is not apparent from the description what the repeating stack segment actually is.

**Comment by selvakumar7991** [comment]
@jglick thanks for replying and appreciate your time and effort

they are three steps to reproduce the issue and shared the screenshot as well 

1. added the Stashed File Parameter parameter in the jenkins pipeline  by enabling the "project is parameterised"
<img width="1560" alt="parameter" src="https://github.com/jenkinsci/file-parameters-plugin/assets/18574716/0e26c316-79f4-4e1c-9875-1c0bfae48049">
2. Click on build with parameters button, and then click on build of jenkins job
<img width="1081" alt="build" src="https://github.com/jenkinsci/file-parameters-plugin/assets/18574716/196172b9-1702-4733-9775-27c5ee1cfc3b">
3. followed that, it showed the white screen
<img width="1092" alt="white screen" src="https://github.com/jenkinsci/file-parameters-plugin/assets/18574716/e6c96e68-5f89-4ac5-8768-ab8ad4283b96">

the repeating stack error in log are attached to see more about ir
[jenkins-master (2).txt](https://github.com/jenkinsci/file-parameters-plugin/files/13828999/jenkins-master.2.txt)

**Comment by selvakumar7991** [comment]
**ERROR logs are attached in file**

**Comment by selvakumar7991** [comment]
@jglick hoping attached all required files

**Comment by jglick** [comment]
```
org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:519)
org.datadog.jenkins.plugins.datadog.model.BuildData.<init>(BuildData.java:150)
org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator.<init>(DatadogTaskListenerDecorator.java:49)
org.datadog.jenkins.plugins.datadog.logs.DatadogTaskListenerDecorator$Factory.of(DatadogTaskListenerDecorator.java:82)
org.jenkinsci.plugins.workflow.log.TaskListenerDecorator.lambda$apply$3(TaskListenerDecorator.java:164)
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
…
java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
org.jenkinsci.plugins.workflow.log.TaskListenerDecorator.apply(TaskListenerDecorator.java:166)
org.jenkinsci.plugins.workflow.job.WorkflowRun.getListener(WorkflowRun.java:236)
org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.getListener(WorkflowRun.java:1024)
io.jenkins.plugins.file_parameters.StashedFileParameterValue.buildEnvironment(StashedFileParameterValue.java:70)
hudson.model.ParametersAction.buildEnvironment(ParametersAction.java:143)
hudson.model.Run.getEnvironment(Run.java:2434)
org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:519)
```

probably needs to be fixed in the Datadog plugin. There is no apparent reason why `DatadogTaskListenerDecorator` would need to look up the `BuildData` so eagerly. Better report it there. In the meantime, pick one plugin to uninstall.
