### ISSUE TITLE
unable to install 110.vbe06c86f5235 (dependency issue?)

### ISSUE THREAD

**Issue by jmatzdorff-cpi** [jenkinsci/file-parameters-plugin#36]
jenkins isn't updating this plugin to 110.vbe06c86f5235 -- at first i thought it may be a dependency issue, but the dependencies are all updated (struct is at 1.22 and workflow-api is 2.42).  jenkins core is updated to 2.277.1.

i'm actually unsure what info to capture to figure out why it's being blocked from updating.  screenshot is unlikely helpful, but included.  i was updating to verify https://github.com/jenkinsci/file-parameters-plugin/issues/26

![Screen Shot 2021-03-18 at 9 50 40 AM](https://user-images.githubusercontent.com/38891812/111664822-6789db80-87cf-11eb-99fd-5af82a59a0ef.png)

happy to grab more info if you tell me what to get.

**Comment by jglick** [comment]
Just use https://github.com/jenkinsci/file-parameters-plugin/releases/tag/99.102.vbc6a133bcbbb. Your Jenkins version is not new enough for the very latest version.

**Comment by jmatzdorff-cpi** [comment]
ahh.... this is not for LTS releases.  sorry didn't realize that.
