### ISSUE TITLE
Integrate file-parameters with job-dsl-plugin

### ISSUE THREAD

**Issue by theatricshrink** [jenkinsci/file-parameters-plugin#59]
Hey,

This awesome plugin solves a lot of problems we had in the past where file parameters were very tough to use with pipeline.
One great improvement for us would be to integrate the new Stashed and Base64 File Parameters with the dsl plugin. So we would be able to create these new parameters in dsl jobs as well.

Thanks

**Comment by jglick** [comment]
Better to file this under `job-dsl`. IIUC you can always use a fallback configuration style and the plugin simply offers convenient shortcuts for common cases. (I would like it to support `@Symbol` but apparently it does not.)

**Comment by tiagomlalves** [comment]
Thanks @jglick for the quick reply. I'm not following your suggestion, could you please give a few more details?

I'm not sure if by "fallback configuration style" you mean using the [configure block](https://github.com/jenkinsci/job-dsl-plugin/wiki/The-Configure-Block). If it is, I managed to do that with the below:

```
pipelineJob('...') {
  ...
  
  configure { project ->
    def parameterDefinitions = project / 'properties' / 'hudson.model.ParametersDefinitionProperty' / 'parameterDefinitions'

    parameterDefinitions << 'io.jenkins.plugins.file__parameters.StashedFileParameterDefinition'(plugin: 'file-parameters') {
      name('Upload_File')
    }
  }
  
  ...
}
```

This appends a parameter called `Upload_File` to the defined parameter list. To generate the parameter in the correct location one simple needs to generate the parameters that come before this one, then use this block, and then generate the remaining parameters.

**Comment by jglick** [comment]
I am not very familiar with `job-dsl`. My understanding was that it did support a less pretty syntax by which any `Describable` objects could be expressed. And I think I recall something recently changing w.r.t. `@Symbol`. That is all I know. If you want any other help, again I would recommend filing an issue in the `job-dsl-plugin` repo or Jira component, whichever it uses.
